# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
# Basic tutorial: http://symfony.com/doc/current/reference/configuration/security.html
# how to load users from db: http://symfony.com/doc/current/security/entity_provider.html
# how to build a traditional login form: http://symfony.com/doc/current/security/form_login_setup.html

security:
    encoders:
       FOS\UserBundle\Model\UserInterface: bcrypt
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                check_path: fos_user_security_check
                login_path: fos_user_security_login
            logout:
                path: fos_user_security_logout
                target: /
            anonymous: true


    access_control:
        - { path: ^/[^/]+/admin, role: ROLE_ADMIN }
        - { path: ^/[^/]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/profile/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
